# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run L0 cut-pursuit graph partitioning
#'
#' Mirrors \code{crownCluster.init_cutpursuit()} from TreeAIBox.
#' Takes a point cloud (n_nodes x D observation matrix), a KNN edge list,
#' and returns a component label per node (0-based).
#'
#' @param obs        numeric matrix (n_nodes x D).  For CrownClustersSP, D=3
#'                   and the rows are the XYZ of each decimated point.
#' @param Eu         integer vector of 0-based edge source indices.
#' @param Ev         integer vector of 0-based edge target indices.
#' @param edge_weights numeric vector of edge weights (length n_edges).
#'                   Pass \code{rep(1, n_edges)} for uniform weights.
#' @param node_weights numeric vector of node weights (length n_nodes).
#'                   Pass \code{rep(1, n_nodes)} for uniform weights.
#' @param lambda     regularisation strength (TreeAIBox default: 1.0).
#' @param cutoff     minimum component size (0 = no minimum).
#' @param mode       fidelity: 1.0 = L2 (default for crown blobs).
#' @param speed      0=slow, 1=standard (default), 2=fast, 3=ludicrous.
#' @param weight_decay edge-weight decay (0 = no decay).
#' @param verbose    0 = silent.
#' @return integer vector length n_nodes: component index (0-based) per node.
#' @export
cut_pursuit_l0_rcpp <- function(obs, Eu, Ev, edge_weights, node_weights, lambda = 1.0, cutoff = 0L, mode = 1.0, speed = 1.0, weight_decay = 0.0, verbose = 0.0) {
    .Call(`_treeAIBoxR_cut_pursuit_l0_rcpp`, obs, Eu, Ev, edge_weights, node_weights, lambda, cutoff, mode, speed, weight_decay, verbose)
}

#' Build component-level node graph with true minimum point-to-point distances
#'
#' Faithfully replicates \code{stemCluster.create_node_graph()} /
#' \code{crownCluster.create_node_graph()} from TreeAIBox.
#'
#' For each component, the k nearest component-neighbours (by centroid) are
#' found.  For each candidate pair, the actual minimum 3-D point-to-point
#' distance and the 2-D XY centroid-to-centroid distance are computed.
#' Edges where \code{dist2d >= max_dist_2d} are dropped.  The remaining
#' edges are returned so the R caller can build an igraph and run Dijkstra.
#'
#' @param xyz       numeric matrix (n_pts x 3).  Points of the decimated cloud.
#' @param labels    integer vector length n_pts.  0-based component label per
#'                  decimated point (e.g. from \code{cut_pursuit_l0_rcpp}).
#' @param k         number of nearest component-centroid neighbours to consider
#'                  per component (TreeAIBox default: 20).
#' @param max_dist_2d  2-D XY distance threshold.  Pairs farther than this are
#'                  dropped (TreeAIBox: \code{max_isolated_distance} = 0.3 m
#'                  for both stemCluster and crownCluster).
#' @return A list with elements:
#'   \item{from}{integer vector: 1-based source component node index}
#'   \item{to}{integer vector: 1-based target component node index}
#'   \item{dist3d}{numeric: true minimum 3-D point-to-point distance}
#'   \item{dist2d}{numeric: 2-D XY centroid distance}
#'   \item{n_comps}{integer: total number of unique components}
#' @export
create_node_graph_rcpp <- function(xyz, labels, k = 20L, max_dist_2d = 0.3) {
    .Call(`_treeAIBoxR_create_node_graph_rcpp`, xyz, labels, k, max_dist_2d)
}

