// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cut_pursuit_l0_rcpp
Rcpp::IntegerVector cut_pursuit_l0_rcpp(Rcpp::NumericMatrix obs, Rcpp::IntegerVector Eu, Rcpp::IntegerVector Ev, Rcpp::NumericVector edge_weights, Rcpp::NumericVector node_weights, double lambda, int cutoff, double mode, double speed, double weight_decay, double verbose);
RcppExport SEXP _treeAIBoxR_cut_pursuit_l0_rcpp(SEXP obsSEXP, SEXP EuSEXP, SEXP EvSEXP, SEXP edge_weightsSEXP, SEXP node_weightsSEXP, SEXP lambdaSEXP, SEXP cutoffSEXP, SEXP modeSEXP, SEXP speedSEXP, SEXP weight_decaySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Eu(EuSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Ev(EvSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_weights(edge_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type node_weights(node_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type speed(speedSEXP);
    Rcpp::traits::input_parameter< double >::type weight_decay(weight_decaySEXP);
    Rcpp::traits::input_parameter< double >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cut_pursuit_l0_rcpp(obs, Eu, Ev, edge_weights, node_weights, lambda, cutoff, mode, speed, weight_decay, verbose));
    return rcpp_result_gen;
END_RCPP
}
// create_node_graph_rcpp
List create_node_graph_rcpp(NumericMatrix xyz, IntegerVector labels, int k, double max_dist_2d);
RcppExport SEXP _treeAIBoxR_create_node_graph_rcpp(SEXP xyzSEXP, SEXP labelsSEXP, SEXP kSEXP, SEXP max_dist_2dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist_2d(max_dist_2dSEXP);
    rcpp_result_gen = Rcpp::wrap(create_node_graph_rcpp(xyz, labels, k, max_dist_2d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treeAIBoxR_cut_pursuit_l0_rcpp", (DL_FUNC) &_treeAIBoxR_cut_pursuit_l0_rcpp, 11},
    {"_treeAIBoxR_create_node_graph_rcpp", (DL_FUNC) &_treeAIBoxR_create_node_graph_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_treeAIBoxR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
